### ISSUE TITLE
Todo!

### ISSUE THREAD

**Issue by sarahkemi** [sarahkemi/rhythm-face#1]
#### to obtain basic meeting mediator functionality:
- [x] deploy web interface to heroku
- [ ] add meeting mediator to web view in app
- [ ] figure out how to input room name/id and user name/id [login on android side?]
- [ ] meeting mediator needs list of active room participants
- [ ] need android audio data to inject into JS [check that the format matches server's utterance format]
#### to combine face tracking and meeting mediator:
- [ ] add face tracking service to rhythm server
- [ ] update d3 visualization with face tracking data
